# Generated by Django 4.2.23 on 2025-08-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_email_4b85f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_usernam_baeb4b_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "SuperAdmin"), (2, "Admin"), (3, "User")]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "user_type")},
        ),
        migrations.RemoveField(
            model_name="user",
            name="isApproved",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updatedAt",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
