# Generated by Django 5.0.2 on 2025-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projectId',
            field=models.JSONField(null=True),
        ),
    ]
