# Generated by Django 5.0.2 on 2025-08-15 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_user_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedImage', models.CharField(blank=True, max_length=500, null=True)),
                ('templateImage', models.CharField(blank=True, max_length=500, null=True)),
                ('markTag', models.JSONField(blank=True, null=True)),
                ('latLng', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.project')),
                ('uploadedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userTaskList',
            },
        ),
    ]
