# Generated by Django 5.0.2 on 2025-08-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_usertasklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
