# Generated by Django 5.0.2 on 2025-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
