# Generated by Django 5.0.2 on 2025-08-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_project_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasklist',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.project'),
        ),
    ]
